package:
  name: image-extractor
  version: "0.6.0"

source:
  git_rev: v0.6.0
  git_url: https://github.com/cta-observatory/image-extractor.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python

  test:
    imports:
      -image-extractor

about:
  home: https://github.com/cta-observatory/image-extractor
  license: MIT
  license_file: LICENSE
