package:
  name: dl1-data-dumper
  version: "0.6.0"

source:
  git_rev: v0.6.0
  git_url: https://github.com/cta-observatory/dl1-data-dumper.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python

  test:
    imports:
      -dl1-data-dumper

about:
  home: https://github.com/cta-observatory/dl1-data-dumper
  license: MIT
  license_file: LICENSE
